// Generated by @lattice-ui/preview. Do not edit.
import { Color3, UDim2, UDim, Vector2, typeIs, pairs, error, isPreviewElement, Frame, TextButton, ScreenGui, TextLabel, TextBox, ImageLabel, ScrollingFrame, UICorner, UIPadding, UIListLayout, UIGridLayout, UIStroke, React, Slot } from "@lattice-ui/preview/runtime";
import { useCheckboxContext } from "./context.ts";
import type { CheckboxIndicatorProps } from "./types.ts";
export function CheckboxIndicator(props: CheckboxIndicatorProps) {
    const checkboxContext = useCheckboxContext();
    const visible = checkboxContext.checked !== false;
    const forceMount = props.forceMount === true;
    if (!visible && !forceMount) {
        return undefined;
    }
    const child = props.children;
    if (props.asChild) {
        if (!React.isValidElement(child)) {
            error("[CheckboxIndicator] `asChild` requires a child element.");
        }
        return <Slot Visible={visible}>{child}</Slot>;
    }
    return (<Frame BackgroundColor3={Color3.fromRGB(240, 244, 252)} BorderSizePixel={0} Size={UDim2.fromOffset(12, 12)} Visible={visible}>
      {child}
    </Frame>);
}

