// Generated by @lattice-ui/preview. Do not edit.
import { Color3, UDim2, UDim, Vector2, typeIs, pairs, error, isPreviewElement, Frame, TextButton, ScreenGui, TextLabel, TextBox, ImageLabel, ScrollingFrame, UICorner, UIPadding, UIListLayout, UIGridLayout, UIStroke } from "@lattice-ui/preview/runtime";
import type React from "react";
export type CheckedState = boolean | "indeterminate";
export type CheckboxSetChecked = (checked: CheckedState) => void;
export type CheckboxContextValue = {
    checked: CheckedState;
    setChecked: CheckboxSetChecked;
    disabled: boolean;
    required: boolean;
};
export type CheckboxProps = {
    checked?: CheckedState;
    defaultChecked?: CheckedState;
    onCheckedChange?: (checked: CheckedState) => void;
    disabled?: boolean;
    required?: boolean;
    asChild?: boolean;
    children?: React.ReactNode;
};
export type CheckboxIndicatorProps = {
    forceMount?: boolean;
    asChild?: boolean;
    children?: React.ReactNode;
};

