// Generated by @lattice-ui/preview. Do not edit.
import { Color3, UDim2, UDim, Vector2, typeIs, pairs, error, isPreviewElement, Frame, TextButton, ScreenGui, TextLabel, TextBox, ImageLabel, ScrollingFrame, UICorner, UIPadding, UIListLayout, UIGridLayout, UIStroke, createStrictContext } from "@lattice-ui/preview/runtime";
import type { DialogContextValue } from "./types.ts";
const [DialogContextProvider, useDialogContext] = createStrictContext<DialogContextValue>("Dialog");
export { DialogContextProvider, useDialogContext };

