// Generated by @lattice-ui/preview. Do not edit.
import { Color3, UDim2, UDim, Vector2, typeIs, pairs, error, isPreviewElement, Frame, TextButton, ScreenGui, TextLabel, TextBox, ImageLabel, ScrollingFrame, UICorner, UIPadding, UIListLayout, UIGridLayout, UIStroke, React, Portal, PortalProvider, usePortalContext } from "@lattice-ui/preview/runtime";
import type { DialogPortalProps } from "./types.ts";
function DialogPortalWithOverrides(props: DialogPortalProps) {
    const portalContext = usePortalContext();
    const container = props.container ?? portalContext.container;
    const displayOrderBase = props.displayOrderBase ?? portalContext.displayOrderBase;
    return (<PortalProvider container={container} displayOrderBase={displayOrderBase}>
      <Portal>{props.children}</Portal>
    </PortalProvider>);
}
export function DialogPortal(props: DialogPortalProps) {
    const hasOverrides = props.container !== undefined || props.displayOrderBase !== undefined;
    if (hasOverrides) {
        return (<DialogPortalWithOverrides container={props.container} displayOrderBase={props.displayOrderBase}>
        {props.children}
      </DialogPortalWithOverrides>);
    }
    return <Portal>{props.children}</Portal>;
}

