// Generated by @lattice-ui/preview. Do not edit.
import { Color3, UDim2, UDim, Vector2, typeIs, pairs, error, isPreviewElement, Frame, TextButton, ScreenGui, TextLabel, TextBox, ImageLabel, ScrollingFrame, UICorner, UIPadding, UIListLayout, UIGridLayout, UIStroke, React, useControllableState } from "@lattice-ui/preview/runtime";
import { DialogContextProvider } from "./context.ts";
import type { DialogProps } from "./types.ts";
export function Dialog(props: DialogProps) {
    const [open, setOpenState] = useControllableState<boolean>({
        value: props.open,
        defaultValue: props.defaultOpen ?? false,
        onChange: props.onOpenChange,
    });
    const modal = props.modal ?? true;
    const triggerRef = React.useRef<HTMLElement | null>(null);
    const setOpen = React.useCallback((nextOpen: boolean) => {
        setOpenState(nextOpen);
    }, [setOpenState]);
    const contextValue = React.useMemo(() => ({
        open,
        setOpen,
        modal,
        triggerRef,
    }), [modal, open, setOpen]);
    return <DialogContextProvider value={contextValue}>{props.children}</DialogContextProvider>;
}

