// Generated by @lattice-ui/preview. Do not edit.
import { Color3, UDim2, UDim, Vector2, typeIs, pairs, error, isPreviewElement, Frame, TextButton, ScreenGui, TextLabel, TextBox, ImageLabel, ScrollingFrame, UICorner, UIPadding, UIListLayout, UIGridLayout, UIStroke, React, Slot } from "@lattice-ui/preview/runtime";
import { useDialogContext } from "./context.ts";
import type { DialogCloseProps } from "./types.ts";
export function DialogClose(props: DialogCloseProps) {
    const dialogContext = useDialogContext();
    const handleActivated = React.useCallback(() => {
        dialogContext.setOpen(false);
    }, [dialogContext.setOpen]);
    if (props.asChild) {
        const child = props.children;
        if (!child) {
            error("[DialogClose] `asChild` requires a child element.");
        }
        return <Slot Event={{ Activated: handleActivated }}>{child}</Slot>;
    }
    return (<TextButton AutoButtonColor={false} BackgroundTransparency={1} BorderSizePixel={0} Event={{ Activated: handleActivated }} Size={UDim2.fromOffset(110, 34)} Text="Close" TextColor3={Color3.fromRGB(240, 244, 250)} TextSize={16}>
      {props.children}
    </TextButton>);
}

