// Generated by @lattice-ui/preview. Do not edit.
import { Color3, UDim2, UDim, Vector2, typeIs, pairs, error, isPreviewElement, Frame, TextButton, ScreenGui, TextLabel, TextBox, ImageLabel, ScrollingFrame, UICorner, UIPadding, UIListLayout, UIGridLayout, UIStroke, type LayerInteractEvent } from "@lattice-ui/preview/runtime";
import type React from "react";
export type DialogSetOpen = (open: boolean) => void;
export type DialogContextValue = {
    open: boolean;
    setOpen: DialogSetOpen;
    modal: boolean;
    triggerRef: React.MutableRefObject<(HTMLElement | null) | undefined>;
};
export type DialogProps = {
    open?: boolean;
    defaultOpen?: boolean;
    onOpenChange?: (open: boolean) => void;
    modal?: boolean;
    children?: React.ReactNode;
};
export type DialogTriggerProps = {
    asChild?: boolean;
    disabled?: boolean;
    children?: React.ReactElement;
};
export type DialogPortalProps = {
    container?: HTMLElement | null;
    displayOrderBase?: number;
    children?: React.ReactNode;
};
export type DialogOverlayProps = {
    asChild?: boolean;
    forceMount?: boolean;
    children?: React.ReactElement;
};
export type DialogContentProps = {
    forceMount?: boolean;
    trapFocus?: boolean;
    restoreFocus?: boolean;
    onEscapeKeyDown?: (event: LayerInteractEvent) => void;
    onPointerDownOutside?: (event: LayerInteractEvent) => void;
    onInteractOutside?: (event: LayerInteractEvent) => void;
    children?: React.ReactNode;
};
export type DialogCloseProps = {
    asChild?: boolean;
    children?: React.ReactElement;
};

