/**
 * Gallery-mode helpers: target discovery (a dependency-free `**\/*.loom.tsx`
 * glob over the project tree), the `virtual:loom-targets` module codegen, and
 * the static-build codegen. Pure and node-only so each piece is unit-testable
 * without a Vite server.
 *
 * These live in `@loom-dev/preview` (not the CLI) because the Vite plugin owns
 * gallery mode — `loomPreview({ targets })` gives a plain `vite.config.ts` the
 * same gallery `loom preview --targets` does. The CLI consumes them through
 * `@loom-dev/preview/gallery`.
 */
import { type Dirent, readdirSync } from "node:fs";
import { join, resolve, win32 } from "node:path";
import { toViteFsUrl } from "./vite-fs-url.ts";

// Re-exported so a consumer (the CLI's static build) has one import for
// everything gallery-shaped.
export {
	GALLERY_SHELL_PATH,
	GLOBALS_PATH,
	LOOM_REPO_ROOT,
} from "./paths.ts";
export { toViteFsUrl } from "./vite-fs-url.ts";

/** Glob used when `targets` is passed without a value (or a bare directory). */
export const DEFAULT_TARGETS_GLOB = "**/*.loom.tsx";

/**
 * Target discovery input: a glob, a directory, a list of either, or `true` for
 * the default `**\/*.loom.tsx`.
 */
export type TargetsInput = string | string[] | true;

/**
 * Compile one glob to a RegExp over posix-style relative paths.
 * Supports `**` (any depth, including none when written `**\/`) and `*`
 * (anything but `/`). Everything else is matched literally.
 */
export function globToRegExp(glob: string): RegExp {
	const GLOBSTAR_SLASH = "\u0001"; // placeholder for `**/`
	const GLOBSTAR = "\u0002"; // placeholder for `**`
	const escaped = glob.replace(/[.+^${}()|[\]\\]/g, "\\$&");
	const source = escaped
		.replaceAll("**/", GLOBSTAR_SLASH)
		.replaceAll("**", GLOBSTAR)
		.replaceAll("*", "[^/]*")
		.replaceAll(GLOBSTAR_SLASH, "(?:.*/)?")
		.replaceAll(GLOBSTAR, ".*");
	return new RegExp(`^${source}$`);
}

/**
 * Normalize the `targets` value into discovery globs. `true` → the default
 * glob; a plain directory (no `*`) → `<dir>/**\/*.loom.tsx`; anything with a
 * wildcard is used as-is.
 */
export function normalizeTargetsPatterns(value: TargetsInput): string[] {
	const raw =
		value === true
			? [DEFAULT_TARGETS_GLOB]
			: typeof value === "string"
				? [value]
				: value;
	const patterns: string[] = [];
	for (const entry of raw) {
		const cleaned = entry.replace(/^\.\//, "").replace(/\/+$/, "");
		if (cleaned === "" || cleaned === ".") patterns.push(DEFAULT_TARGETS_GLOB);
		else if (cleaned.includes("*")) patterns.push(cleaned);
		else patterns.push(`${cleaned}/${DEFAULT_TARGETS_GLOB}`);
	}
	return patterns;
}

/**
 * Recursively find files under `root` matching any of the globs. Skips
 * `node_modules` and dot-directories. Returns sorted posix-style relative
 * paths.
 */
export function findLoomTargets(root: string, patterns: string[]): string[] {
	const regexes = patterns.map(globToRegExp);
	const found: string[] = [];
	const walk = (dir: string, relPrefix: string): void => {
		let entries: Dirent[];
		try {
			entries = readdirSync(dir, { withFileTypes: true });
		} catch {
			return; // unreadable dir: not fatal for discovery
		}
		for (const entry of entries) {
			if (entry.name === "node_modules" || entry.name.startsWith(".")) continue;
			const rel = relPrefix === "" ? entry.name : `${relPrefix}/${entry.name}`;
			if (entry.isDirectory()) walk(join(dir, entry.name), rel);
			else if (entry.isFile() && regexes.some((re) => re.test(rel)))
				found.push(rel);
		}
	};
	walk(root, "");
	return found.sort();
}

/**
 * Emit the `virtual:loom-targets` module body. Each target maps its relative
 * path to a lazy `import()` of the absolute file via Vite's `/@fs/` URL space
 * (so it resolves regardless of the server root). Paths are JSON-escaped.
 */
export function generateTargetsModule(
	root: string,
	relPaths: string[],
): string {
	const entries = relPaths.map((rel) => {
		const segments = rel.split(/[\\/]/);
		const windowsAbsolute =
			/^[A-Za-z]:[\\/]/.test(root) || root.startsWith("\\\\");
		const abs = windowsAbsolute
			? win32.resolve(root, ...segments)
			: resolve(root, ...segments);
		return `\t${JSON.stringify(rel)}: () => import(${JSON.stringify(toViteFsUrl(abs))}),`;
	});
	return `// generated by loom --targets\nexport const targets = {\n${entries.join("\n")}\n};\n`;
}

// ---------------------------------------------------------------------------
// Static-build codegen + URL contract.
//
// `vite build` emits a self-contained SPA. Unlike the dev server's virtual
// modules (which lean on `/@fs/` URLs only Vite's dev middleware understands),
// the build hands Rollup a real module graph: `index.html` → `entry.ts` →
// { globals, targets, shell }. Every specifier is *relative* (computed against
// the project root, where the plugin places its generated modules) — a leading
// `/` would mean root-relative to Vite, not an absolute fs path — so Rollup can
// follow each one and code-split each `*.loom.tsx` into its own async chunk.
// ---------------------------------------------------------------------------

// The browser-side URL contract lives in `./gallery/params` (no node imports)
// so the bundled shell can use it; re-exported here for the node-side test.
export {
	type GalleryParams,
	parseBackgroundColor,
	parseGalleryParams,
} from "./gallery/params.ts";

/**
 * The static-build entry module. `globalsSpecifier` is imported **first** so
 * `installGlobals()` runs before the shell/target graph evaluates (roblox-ts
 * modules call `game.GetService(...)` at module top level). ESM evaluates
 * imported modules depth-first in source order, so this ordering is guaranteed.
 */
export function generateBuildEntryModule(opts: {
	globalsSpecifier: string;
	targetsSpecifier: string;
	shellSpecifier: string;
}): string {
	return (
		`// generated by loom build\n` +
		`import ${JSON.stringify(opts.globalsSpecifier)};\n` +
		`import { targets } from ${JSON.stringify(opts.targetsSpecifier)};\n` +
		`import { startGallery } from ${JSON.stringify(opts.shellSpecifier)};\n` +
		`startGallery(targets);\n`
	);
}

/**
 * The static-build targets module. Each entry lazily `import()`s a target via a
 * plain relative specifier (Rollup follows it into an async chunk). Callers pass
 * specifiers already made relative to the scratch entry dir.
 */
export function generateBuildTargetsModule(
	entries: Array<{ key: string; specifier: string }>,
): string {
	const body = entries
		.map(
			({ key, specifier }) =>
				`\t${JSON.stringify(key)}: () => import(${JSON.stringify(specifier)}),`,
		)
		.join("\n");
	return `// generated by loom build\nexport const targets = {\n${body}\n};\n`;
}
