import * as React from "react";

export default React;
export {
	__CLIENT_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE,
	__COMPILER_RUNTIME,
	Activity,
	act,
	Children,
	Component,
	cache,
	cacheSignal,
	captureOwnerStack,
	cloneElement,
	createContext,
	createElement,
	createRef,
	Fragment,
	forwardRef,
	isValidElement,
	lazy,
	memo,
	Profiler,
	PureComponent,
	StrictMode,
	Suspense,
	startTransition,
	unstable_useCacheRefresh,
	use,
	useActionState,
	useCallback,
	useContext,
	useDebugValue,
	useDeferredValue,
	useEffect,
	useEffectEvent,
	useId,
	useImperativeHandle,
	useInsertionEffect,
	useLayoutEffect,
	useMemo,
	useOptimistic,
	useReducer,
	useRef,
	useState,
	useSyncExternalStore,
	useTransition,
	version,
} from "react";
