// Generated by @lattice-ui/preview. Do not edit.
import { Color3, UDim2, UDim, Vector2, typeIs, pairs, error, isPreviewElement, Frame, TextButton, ScreenGui, TextLabel, TextBox, ImageLabel, ScrollingFrame, UICorner, UIPadding, UIListLayout, UIGridLayout, UIStroke, createStrictContext } from "@lattice-ui/preview/runtime";
import type { SwitchContextValue } from "./types.ts";
const [SwitchContextProvider, useSwitchContext] = createStrictContext<SwitchContextValue>("Switch");
export { SwitchContextProvider, useSwitchContext };

