// Generated by @lattice-ui/preview. Do not edit.
import { Color3, UDim2, UDim, Vector2, typeIs, pairs, error, isPreviewElement, Frame, TextButton, ScreenGui, TextLabel, TextBox, ImageLabel, ScrollingFrame, UICorner, UIPadding, UIListLayout, UIGridLayout, UIStroke, React, Slot } from "@lattice-ui/preview/runtime";
import { useSwitchContext } from "./context.ts";
import type { SwitchThumbProps } from "./types.ts";
export function SwitchThumb(props: SwitchThumbProps) {
    const switchContext = useSwitchContext();
    const visible = switchContext.checked;
    const forceMount = props.forceMount === true;
    if (!visible && !forceMount) {
        return undefined;
    }
    const child = props.children;
    if (props.asChild) {
        if (!React.isValidElement(child)) {
            error("[SwitchThumb] `asChild` requires a child element.");
        }
        return <Slot Visible={visible}>{child}</Slot>;
    }
    return (<Frame BackgroundColor3={Color3.fromRGB(240, 244, 252)} BorderSizePixel={0} Size={UDim2.fromOffset(16, 16)} Visible={visible}>
      {child}
    </Frame>);
}

