// Generated by @lattice-ui/preview. Do not edit.
import { Color3, UDim2, UDim, Vector2, typeIs, pairs, error, isPreviewElement, Frame, TextButton, ScreenGui, TextLabel, TextBox, ImageLabel, ScrollingFrame, UICorner, UIPadding, UIListLayout, UIGridLayout, UIStroke } from "@lattice-ui/preview/runtime";
import type React from "react";
export type SwitchSetChecked = (checked: boolean) => void;
export type SwitchContextValue = {
    checked: boolean;
    setChecked: SwitchSetChecked;
    disabled: boolean;
};
export type SwitchProps = {
    checked?: boolean;
    defaultChecked?: boolean;
    onCheckedChange?: (checked: boolean) => void;
    disabled?: boolean;
    asChild?: boolean;
    children?: React.ReactNode;
};
export type SwitchThumbProps = {
    forceMount?: boolean;
    asChild?: boolean;
    children?: React.ReactNode;
};

