// Generated by @lattice-ui/preview. Do not edit.
import { Color3, UDim2, UDim, Vector2, typeIs, pairs, error, isPreviewElement, Frame, TextButton, ScreenGui, TextLabel, TextBox, ImageLabel, ScrollingFrame, UICorner, UIPadding, UIListLayout, UIGridLayout, UIStroke } from "@lattice-ui/preview/runtime";
import { DialogClose } from "./Dialog/DialogClose.tsx";
import { DialogContent } from "./Dialog/DialogContent.tsx";
import { DialogOverlay } from "./Dialog/DialogOverlay.tsx";
import { DialogPortal } from "./Dialog/DialogPortal.tsx";
import { Dialog as DialogRoot } from "./Dialog/DialogRoot.tsx";
import { DialogTrigger } from "./Dialog/DialogTrigger.tsx";
export const Dialog = {
    Root: DialogRoot,
    Trigger: DialogTrigger,
    Portal: DialogPortal,
    Content: DialogContent,
    Overlay: DialogOverlay,
    Close: DialogClose,
} as const satisfies {
    Root: typeof DialogRoot;
    Trigger: typeof DialogTrigger;
    Portal: typeof DialogPortal;
    Content: typeof DialogContent;
    Overlay: typeof DialogOverlay;
    Close: typeof DialogClose;
};
export { DialogClose, DialogContent, DialogOverlay, DialogPortal, DialogRoot, DialogTrigger };
export type { DialogCloseProps, DialogContentProps, DialogOverlayProps, DialogPortalProps, DialogProps, DialogTriggerProps, } from "./Dialog/types.ts";

