import * as React from "react";
import { LayoutProvider, useLayoutEngineStatus, useRobloxLayout } from "./layout";
import { createStrictContext, DismissableLayer, FocusScope, Portal, PortalProvider, Presence, Slot, useControllableState } from "./react";
import { __previewGlobal, Color3, error, game, isPreviewElement, math, next, type PreviewRuntimeGlobalTarget, pairs, TweenInfo, typeIs, UDim, UDim2, Vector2, Vector3, warn, workspace } from "./runtime";
export type SetupRobloxEnvironmentTarget = PreviewRuntimeGlobalTarget;
/**
 * Vite alias note:
 * - Alias broad packages such as `@rbxts/services` or `@flamework/core` to small local shim files.
 * - Re-export only the browser-safe members you need from this package in those shims.
 * - See `README.md` for concrete examples.
 */
export declare function setupRobloxEnvironment(target?: SetupRobloxEnvironmentTarget): PreviewRuntimeGlobalTarget;
declare const previewRuntimeHosts: {
    BillboardGui: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    CanvasGroup: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    Frame: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    ImageLabel: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    ImageButton: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    ScreenGui: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    ScrollingFrame: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    SurfaceGui: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    TextBox: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    TextButton: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    TextLabel: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    UIAspectRatioConstraint: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    UICorner: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    UIFlexItem: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    UIGradient: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    UIGridLayout: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    UIListLayout: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    UIPageLayout: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    UIPadding: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    UIScale: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    UISizeConstraint: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    UIStroke: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    UITableLayout: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    UITextSizeConstraint: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    VideoFrame: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
    ViewportFrame: React.ForwardRefExoticComponent<Omit<import("./hosts").PreviewDomProps, "ref"> & React.RefAttributes<HTMLElement>>;
};
declare const previewRuntimeHelpers: {
    Enum: import("./runtime").PreviewEnumRoot;
    RunService: import("./runtime").PreviewRunService;
    TweenInfo: typeof TweenInfo;
    game: import("./runtime").PreviewGame;
    task: import("./runtime").TaskLibrary;
    workspace: import("./runtime").PreviewWorkspace;
    Color3: typeof Color3;
    error: typeof error;
    math: Readonly<{
        abs: (x: number) => number;
        acos: (x: number) => number;
        asin: (x: number) => number;
        atan: (value: number, x?: number) => number;
        atan2: (y: number, x: number) => number;
        ceil: (x: number) => number;
        clamp: (value: number, min: number, max: number) => number;
        cos: (x: number) => number;
        deg: (value: number) => number;
        exp: (x: number) => number;
        floor: (x: number) => number;
        fmod: (left: number, right: number) => number;
        huge: number;
        log: (value: number, base?: number) => number;
        max: (...values: number[]) => number;
        min: (...values: number[]) => number;
        modf: (value: number) => readonly [number, number];
        pi: number;
        pow: (x: number, y: number) => number;
        rad: (value: number) => number;
        random: {
            (): number;
            (upper: number): number;
            (lower: number, upper: number): number;
        };
        round: (value: number) => number;
        sign: (value: number) => 0 | 1 | -1;
        sin: (x: number) => number;
        sqrt: (x: number) => number;
        tan: (x: number) => number;
    }>;
    next: typeof next;
    os: Readonly<{
        clock: () => number;
    }>;
    pairs: typeof pairs;
    print: typeof import("./runtime").print;
    string: Readonly<{
        find: (value: string, pattern: string, init?: number, plain?: boolean) => readonly [number, number] | undefined;
        gsub: (value: string, pattern: string, replacement: string | ((match: string, ...captures: string[]) => unknown)) => readonly [string, number];
        lower: (value: string) => string;
        sub: (value: string, start?: number, finish?: number) => string;
        upper: (value: string) => string;
    }>;
    tostring: typeof import("./runtime").tostring;
    typeIs: typeof typeIs;
    warn: typeof warn;
    UDim: typeof UDim;
    UDim2: typeof UDim2;
    Vector2: typeof Vector2;
    Vector3: typeof Vector3;
    __previewGlobal: typeof __previewGlobal;
    isPreviewElement: typeof isPreviewElement;
};
declare const previewRuntimePrimitives: {
    DismissableLayer: typeof DismissableLayer;
    FocusScope: typeof FocusScope;
    LayoutProvider: typeof LayoutProvider;
    Portal: typeof Portal;
    PortalProvider: typeof PortalProvider;
    Presence: typeof Presence;
    Slot: React.ForwardRefExoticComponent<Omit<{
        [key: string]: unknown;
        Active?: boolean;
        AnchorPoint?: import("./internal/robloxValues").Vector2Like;
        AutoButtonColor?: boolean;
        AutomaticSize?: string;
        AspectRatio?: number;
        BackgroundColor3?: import("./runtime").Color3Value;
        BackgroundTransparency?: number;
        BorderSizePixel?: number;
        CellPadding?: import("./internal/robloxValues").UDim2Like;
        CellSize?: import("./internal/robloxValues").UDim2Like;
        CanvasSize?: import("./internal/robloxValues").UDim2Like;
        Change?: {
            Text?: (element: HTMLInputElement) => void;
        };
        Color?: import("./runtime").Color3Value;
        CornerRadius?: unknown;
        DominantAxis?: string;
        Event?: import("./hosts").PreviewEventTable;
        FillDirection?: string;
        FillDirectionMaxCells?: number;
        Font?: unknown;
        FlexMode?: string;
        GrowRatio?: number;
        HorizontalAlignment?: string;
        HorizontalFlex?: string;
        Id?: string;
        Image?: string;
        ImageColor3?: import("./runtime").Color3Value;
        ImageTransparency?: number;
        ItemLineAlignment?: string;
        LayoutOrder?: number;
        MaxSize?: import("./internal/robloxValues").Vector2Like;
        MaxTextSize?: number;
        MinSize?: import("./internal/robloxValues").Vector2Like;
        MinTextSize?: number;
        Modal?: boolean;
        Name?: string;
        PaddingBottom?: unknown;
        PaddingBetweenItems?: unknown;
        PaddingLeft?: unknown;
        PaddingRight?: unknown;
        PaddingTop?: unknown;
        Padding?: unknown;
        ParentId?: string;
        PlaceholderText?: string;
        Position?: import("./internal/robloxValues").UDim2Like;
        Rotation?: number;
        ScrollBarThickness?: number;
        ScrollingDirection?: string;
        Scale?: number;
        Selectable?: boolean;
        ShrinkRatio?: number;
        Size?: import("./internal/robloxValues").UDim2Like;
        SizeConstraint?: string;
        SortOrder?: string;
        StartCorner?: string;
        Text?: unknown;
        TextColor3?: import("./runtime").Color3Value;
        TextEditable?: boolean;
        TextScaled?: boolean;
        TextSize?: number;
        TextTransparency?: number;
        TextWrapped?: boolean;
        TextXAlignment?: string;
        TextYAlignment?: string;
        Thickness?: number;
        Transparency?: number;
        VerticalAlignment?: string;
        VerticalFlex?: string;
        Visible?: boolean;
        Wraps?: boolean;
        ZIndex?: number;
        children?: React.ReactNode;
        className?: string;
        style?: React.CSSProperties;
    } & React.HTMLAttributes<HTMLElement> & React.InputHTMLAttributes<HTMLInputElement> & React.ImgHTMLAttributes<HTMLImageElement> & {
        children?: React.ReactNode;
    }, "ref"> & React.RefAttributes<HTMLElement>>;
    createStrictContext: typeof createStrictContext;
    useControllableState: typeof useControllableState;
    useLayoutEngineStatus: typeof useLayoutEngineStatus;
    useRobloxLayout: typeof useRobloxLayout;
};
export { BillboardGui, CanvasGroup, Frame, ImageButton, ImageLabel, ScreenGui, ScrollingFrame, SurfaceGui, TextBox, TextButton, TextLabel, UIAspectRatioConstraint, UICorner, UIFlexItem, UIGradient, UIGridLayout, UIListLayout, UIPadding, UIPageLayout, UIScale, UISizeConstraint, UIStroke, UITableLayout, UITextSizeConstraint, VideoFrame, ViewportFrame, } from "./hosts";
export { PreviewTargetShell } from "./hosts/preview-targets/PreviewTargetShell";
export type { PreviewLayoutDebugNode, PreviewLayoutDebugPayload, PreviewLayoutHostMetadata, PreviewLayoutNode, } from "./layout";
export { areViewportsEqual, createViewportSize, createWindowViewport, getPreviewLayoutProbeSnapshot, initializeLayoutEngine, isViewportLargeEnough, LayoutProvider, loadPreviewLayoutEngineWasmBytes, measureElementViewport, type PreviewLayoutEngineInitOptions, type PreviewLayoutEngineLoader, type PreviewLayoutEngineModuleOrPath, type PreviewLayoutProbeSnapshot, pickViewport, setPreviewLayoutEngineLoader, subscribePreviewLayoutProbe, useLayoutEngineStatus, usePreviewLayoutProbeSnapshot, useRobloxLayout, type ViewportSize, } from "./layout";
export type { PreviewComponentPropsMetadata, PreviewPropMetadata, } from "./preview";
export { AutoMockProvider, buildAutoMockProps, type PreviewAutoMockableComponent, withAutoMockedProps, } from "./preview";
export type { LayerInteractEvent } from "./react";
export { DismissableLayer, FocusScope, Portal, PortalProvider, Presence, usePortalContext, } from "./react";
export type { PreviewEnumCategory, PreviewEnumItem, PreviewEnumRoot, PreviewExecutionMode, PreviewGame, PreviewGuiHitObject, PreviewGuiService, PreviewPlayer, PreviewPlayerGui, PreviewPlayersService, PreviewPolyfillTarget, PreviewRunService, PreviewRuntimeIssue, PreviewRuntimeIssueContext, PreviewRuntimeIssueKind, PreviewRuntimeIssuePhase, PreviewRuntimeIssueSeverity, PreviewRuntimeReporter, PreviewTween, PreviewTweenService, PreviewUserInputService, RBXScriptConnection, RBXScriptSignal, TaskCallback, TaskLibrary, } from "./runtime";
export { clearPreviewRuntimeIssues, Enum, getPreviewRuntimeIssues, getPreviewRuntimeReporter, installPreviewRuntimeGlobals, installPreviewRuntimePolyfills, LayoutExecutionError, LayoutValidationError, ModuleLoadError, normalizePreviewRuntimeError, os, PreviewRuntimeError, previewRuntimeGlobalNames, previewRuntimeGlobalValues, print, publishPreviewRuntimeIssue, RunService, RuntimeMockError, setPreviewRuntimeIssueContext, string, subscribePreviewRuntimeIssues, TransformExecutionError, TransformValidationError, task, UnsupportedPatternError, } from "./runtime";
export { createUniversalRobloxMock, createUniversalRobloxModuleMock, robloxMock, robloxModuleMock, } from "./runtime/robloxMock";
export { __rbxStyle, Box, Text } from "./style/index";
export { __previewGlobal, Color3, createStrictContext, error, game, isPreviewElement, math, next, pairs, React, Slot, TweenInfo, typeIs, UDim, UDim2, useControllableState, Vector2, Vector3, warn, workspace, };
export type PreviewRuntime = {
    hosts: typeof previewRuntimeHosts;
    helpers: typeof previewRuntimeHelpers;
    primitives: typeof previewRuntimePrimitives;
};
export declare const previewRuntime: PreviewRuntime;
