// Generated by @lattice-ui/preview. Do not edit.
import { Color3, UDim2, UDim, Vector2, typeIs, pairs, error, isPreviewElement, Frame, TextButton, ScreenGui, TextLabel, TextBox, ImageLabel, ScrollingFrame, UICorner, UIPadding, UIListLayout, UIGridLayout, UIStroke } from "@lattice-ui/preview/runtime";
import { SwitchRoot } from "./Switch/SwitchRoot.tsx";
import { SwitchThumb } from "./Switch/SwitchThumb.tsx";
export const Switch = {
    Root: SwitchRoot,
    Thumb: SwitchThumb,
} as const;
export type { SwitchContextValue, SwitchProps, SwitchThumbProps } from "./Switch/types.ts";

