// Generated by @lattice-ui/preview. Do not edit.
import { Color3, UDim2, UDim, Vector2, typeIs, pairs, error, isPreviewElement, Frame, TextButton, ScreenGui, TextLabel, TextBox, ImageLabel, ScrollingFrame, UICorner, UIPadding, UIListLayout, UIGridLayout, UIStroke } from "@lattice-ui/preview/runtime";
import { CheckboxIndicator } from "./Checkbox/CheckboxIndicator.tsx";
import { CheckboxRoot } from "./Checkbox/CheckboxRoot.tsx";
export const Checkbox = {
    Root: CheckboxRoot,
    Indicator: CheckboxIndicator,
} as const satisfies {
    Root: typeof CheckboxRoot;
    Indicator: typeof CheckboxIndicator;
};
export { CheckboxIndicator, CheckboxRoot };
export type { CheckboxContextValue, CheckboxIndicatorProps, CheckboxProps, CheckedState } from "./Checkbox/types.ts";

